dkc*: fix some things and add verbosity

diff --git a/docker/dkc b/docker/dkc
--- a/docker/dkc
+++ b/docker/dkc
@@ -4,4 +4,14 @@
 # This also functions as a helper script that grabs the project directory
 # from the `$DKC_PROJ_DIR` environment variable.
 
-exec docker compose --project-directory "${DKC_PROJ_DIR:-$(dkc-get-proj-dir)}" "$@"
+# NOTE: It's not enough to specify --project-directory; projects like seafile
+#   have .env files that reference compose YML files relative to the current
+#   directory
+proj_dir="${DKC_PROJ_DIR:-$(dkc-get-proj-dir)}"
+cd "$proj_dir" || {
+    echo "ERROR: Can't cd to project directory: $proj_dir" >&2
+    exit 1
+}
+
+echo "#❯" docker compose --project-directory "${proj_dir}" "$@"
+exec docker compose --project-directory "${proj_dir}" "$@"
diff --git a/docker/dkc-get-proj-dir b/docker/dkc-get-proj-dir
--- a/docker/dkc-get-proj-dir
+++ b/docker/dkc-get-proj-dir
@@ -67,18 +67,16 @@ IFS="," read -ra compose_files <<<"$compose_files_string"
 declare -A candidates
 
 for i in "${compose_files[@]}"; do
-    if [[ "$i" =~ ^[A-Z]:\\ ]]; then
+    if [[ "$i" =~ ^[A-Za-z]:\\ ]]; then
         proj_dir="${i%\\*}"
         # Skip Windows directories for now
         echo "⚠️ WARNING: Windows path not fully supported yet: $i" >&2
     else
-        if [[ ! -f "$i" ]]; then
-            echo "⚠️ Compose file not found: $i" >&2
-        fi
-
         proj_dir="${i%/*}"
         if [[ ! -d "$proj_dir" ]]; then
             echo "⚠️ Compose project directory not found: $proj_dir" >&2
+        elif [[ ! -f "$i" ]]; then
+            echo "⚠️ Compose file not found: $i" >&2
         fi
     fi
 
